---
- name: Create log directory
  ansible.builtin.file:
    dest: "{{ stolon_pg_log_directory }}"
    state: directory
    owner: "{{ stolon_user }}"
    group: "{{ stolon_group }}"
    mode: "{{ stolon_pg_log_dir_mode }}"
  when: not stolon_pg_log_directory.startswith(stolon_pg_datadir)

- name: Cleanup deprecated log cleanup script
  ansible.builtin.file:
    dest: /etc/cron.d/postgresql
    state: absent
