---
- name: "Create postgres users for {{ pgservice }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_user:
    name: "{{ item }}"
    role_attr_flags: SUPERUSER
    login_host: "{{ stolon_cluster_hosts }}"
    login_port: "{{ cluster.value.sysconfig.stkeeper.pg_port }}"
  environment:
    PGTARGETSESSIONATTRS: read-write
    PGSSLMODE: verify-full
  run_once: true
  loop: "{{ pgusers }}"
  loop_control:
    label: "{{ item }} on {{ cluster.key }}"
  vars:
    pgusers: "{{ cluster.value.pgusers|default(stolon_pgusers) }}"
